---
- name: Install Apache and Start it
  hosts: all
  become: yes

  tasks:
    - name: Install HTTPD
      dnf:
        name: httpd
        state: present

    - name: Start HTTPD
      service:
        name: httpd
        state: started
